### ISSUE TITLE
Add ability to change bot commands prefix 

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/nanami#11]
# Use: 
`!prefix {prefixOfYourChoice}` - sets prefix to your choice.

# Expectation:
Changes command prefix.

# Why
It would be useful in case some of the functionality will be clashing with existing bots.

# TODO:

- [ ] Add ability to change prefix.

**Comment by wisnoi** [comment]
It's a config element ^^;;

**Comment by wisnoi** [comment]
Generally, it has been design that every module has its own prefix, because modules may not always require use of message data -- I will move prefix to be a centralized config element, and modules will take from it for consistency.

**Comment by Jasius** [comment]
> Generally, it has been design that every module has its own prefix, because modules may not always require use of message data -- **I will move prefix to be a centralized config element**, and modules will take from it for consistency.

That's cool, thank you!

**Comment by wisnoi** [comment]
Resolved with 390fadb3b21fe2b966f37dcbfea50ea6f451e1a8.
