### ISSUE TITLE
Commands use permissions

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/nanami#12]
# Command: `!allowlist`

# Use:
`!allowlist {roleId}`
`!allowlist {@role}`

# Expectation: 

- Only members with "administrator" permission can use this command.
- After command usage people within the allowed role will be able to use all of the available non destructive commands.

# TODO:

- [ ] Allow members with administrator permission to use all of the available non destructive commands _(I certainly would love this personally as I tend to be roleless from time to time so it would be convenient if mod would respond to me despite not having moderator role on me)_

- [ ] Allow members with allowed role to use all of the available non destructive commands.

**Comment by wisnoi** [comment]
Seems redundant -- the current goal for permissions is to have modules allow individual restriction based on permission set -- i.e. "ADMINISTRATOR", "SEND_MESSAGES", "MANAGE_CHANNELS" flags. Users with administrator or owner perms are, by default, exceptions to these.

**Comment by Jasius** [comment]
> Seems redundant -- the current goal for permissions is to have modules allow individual restriction based on permission set -- i.e. "ADMINISTRATOR", "SEND_MESSAGES", "MANAGE_CHANNELS" flags. Users with administrator or owner perms are, by default, exceptions to these.

What about trial moderators who have very restrictive permissions compared to full time moderators? How would this work?

**Comment by wisnoi** [comment]
I could make the permissions system based on a string enum for roles /shrug

**Comment by Jasius** [comment]
> I could make the permissions system based on a string enum for roles /shrug

Could you show an example of how it would look like? I think I understand what you mean but it would be nice to be sure that we're on the same page.

Also my idea wasn't very concise in this case as I ignored safe guard that we have in place for trial moderators. Currently trial moderators do not have permissions to kick people but they're allowed to do so with a bot, why was this done? Primarily out of fear of someone malicious infiltrating into the team and thus causing lots of damage with their perms with the use of a self bot, while with bots that we have in place they wouldn't be able to do lots of kicks or bans in rapid succession due to cooldown between actions.

I suppose I'll revisit this issue tomorrow and try to be more specific on what we need and why we need it, hopefully this gave some background on my worries.

**Comment by Jasius** [comment]
Closing this for now as this is far more complicated than I thought initially.
